name: anga
description: "A new Flutter project."
# Prevents accidental publishing to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8

  # Networking
  http: ^1.3.0

  # Charts for weather visualization
  fl_chart: ^1.0.0

  # Animations
  animate_do: ^4.2.0

  # Date formatting
  intl: ^0.20.2 

  # Auto-suggestions (Typeahead)
  flutter_typeahead: ^5.2.0

  # Local storage for user preferences
  shared_preferences: ^2.4.10

  # Page transitions
  page_transition: ^2.2.1

  # State Management
  provider: ^6.1.2

  # Caching
  cached_network_image: ^3.3.1

  # Connectivity
  connectivity_plus: ^6.0.5

  # Local Notifications
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for best practices
  flutter_lints: ^6.0.0

flutter:
  # ✅ Ensure Material icons are enabled
  uses-material-design: true

  # ✅ Declare assets (images, icons, fonts)
  assets:
    - assets/images/farming.jpg
    



